name       : audacious-plugins
version    : 3.8.2
release    : 13
source     :
    - http://distfiles.audacious-media-player.org/audacious-plugins-3.8.2-gtk3.tar.bz2 : 7849024beae61b8af3874b166cf3977905aec77859e53901158b531b31ef0cef
license    : GPL-3.0
component  : multimedia.audio
summary    : Plugins for Audacious music player.
description: |
    Plugins for Audacious music player.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(audacious)
    - pkgconfig(dbus-1)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(flac)
    - pkgconfig(fluidsynth)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libcdio)
    - pkgconfig(libcdio_cdda)
    - pkgconfig(libcddb)
    - pkgconfig(libmms)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpg123)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(neon)
    - pkgconfig(ogg)
    - pkgconfig(sdl2)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - faad-devel
    - ffmpeg-devel
    - lame-devel
setup      : |
    %configure --prefix=/usr \
               --enable-aac=yes \
               --enable-alsa=yes \
               --enable-amidiplug=yes \
               --enable-aosd=yes \
               --enable-cdaudiov \
               --enable-filewriter_mp3=yes \
               --enable-flac=yes \
               --enable-gnomeshortcuts=yes \
               --enable-glspectrum=yes \
               --enable-gtk=yes \
               --enable-hotkey=yes \
               --enable-largefile=yes \
               --enable-modplug=yes \
               --enable-mpg123=yes \
               --enable-mpris2=yes \
               --enable-notify=yes \
               --enable-pulse=yes \
               --enable-sdlout=yes \
               --enable-sndfile=yes \
               --enable-samplerate=yes \
               --enable-songchange=yes \
               --enable-vorbis=yes \
               --enable-wavpack=yes \
               --with-libsdl=2.0
build      : |
    %make
install    : |
    %make_install
