name       : audacious-plugins
version    : 4.0.3
release    : 36
source     :
    - https://distfiles.audacious-media-player.org/audacious-plugins-4.0.3.tar.bz2 : e2a88f5cac3efe03eedbb8d320ca1bb9300788ce66056d2ceba60eb00f8aef97
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Plugins for Audacious music player
description: |
    Plugins for Audacious music player.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(alsa)
    - pkgconfig(audacious)
    - pkgconfig(flac)
    - pkgconfig(fluidsynth)
    - pkgconfig(libavcodec)
    - pkgconfig(libcue)
    - pkgconfig(libcurl)
    - pkgconfig(libcdio_cdda)
    - pkgconfig(libcddb)
    - pkgconfig(libmms)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpg123)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(neon)
    - pkgconfig(sdl2)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - faad-devel
    - lame-devel
setup      : |
    %autogen --enable-qt --disable-gtk
build      : |
    %make
install    : |
    %make_install
