name       : audacious-plugins
version    : '3.8'
release    : 9
source     :
    - http://distfiles.audacious-media-player.org/audacious-plugins-3.8-gtk3.tar.bz2 : 69f53cc6ecc8acd55d6f336aac2c9abc23d887a9e0ba1dfad5456ed970db3a49
license    : GPL-3.0
component  : multimedia.audio
summary    : Plugins for Audacious music player.
description: |
    Plugins for Audacious music player.
rundeps    :
    - audacious
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(audacious)
    - pkgconfig(flac)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmpg123)
    - pkgconfig(libpulse)
    - pkgconfig(neon)
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - faad-devel
    - ffmpeg-devel
setup      : |
    %configure  --prefix=/usr
build      : |
    %make
install    : |
    %make_install
