name       : audacious-plugins
version    : '3.10'
release    : 23
source     :
    - https://github.com/audacious-media-player/audacious-plugins/archive/audacious-plugins-3.10.tar.gz : 3a354c5045eb5d12101c398962b801703c9d3e9180356eb514e3956c5b711781
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Plugins for Audacious music player
description: |
    Plugins for Audacious music player.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(audacious)
    - pkgconfig(dbus-1)
    - pkgconfig(flac)
    - pkgconfig(fluidsynth)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libcdio)
    - pkgconfig(libcdio_cdda)
    - pkgconfig(libcddb)
    - pkgconfig(libmms)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpg123)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(neon)
    - pkgconfig(ogg)
    - pkgconfig(sdl2)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - faad-devel
    - lame-devel
setup      : |
    %autogen --disable-qt --enable-gtk
build      : |
    %make
install    : |
    %make_install
