name       : audacious-plugins
version    : 3.7.1
release    : 7
source     :
    - http://distfiles.audacious-media-player.org/audacious-plugins-3.7.1-gtk3.tar.bz2 : 75469b52694fcfce237a937c6c64c0d355aefa6a7b6c2504ab447d901afc073f
license    : GPL-3.0
component  : multimedia.audio
summary    : Plugins for Audacious music player.
description: |
    Plugins for Audacious music player.
rundeps    :
    - audacious
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(audacious)
    - pkgconfig(flac)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmpg123)
    - pkgconfig(libpulse)
    - pkgconfig(neon)
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - faad-devel
    - ffmpeg-devel
setup      : |
    %configure  --prefix=/usr
build      : |
    %make
install    : |
    %make_install
