name       : audacious-plugins
version    : 4.0.1
release    : 33
source     :
    - https://distfiles.audacious-media-player.org/audacious-plugins-4.0.1.tar.bz2 : 4c439def89aebf10a6a756b2115cb4d2493ecc03cb633b898aea5ac6f10e65ac
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Plugins for Audacious music player
description: |
    Plugins for Audacious music player.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(audacious)
    - pkgconfig(dbus-1)
    - pkgconfig(flac)
    - pkgconfig(fluidsynth)
    - pkgconfig(libavcodec)
    - pkgconfig(libcue)
    - pkgconfig(libcurl)
    - pkgconfig(libcdio)
    - pkgconfig(libcdio_cdda)
    - pkgconfig(libcddb)
    - pkgconfig(libmms)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpg123)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(neon)
    - pkgconfig(ogg)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(sdl2)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - faad-devel
    - lame-devel
setup      : |
    %autogen --enable-qt --disable-gtk
build      : |
    %make
install    : |
    %make_install
