name       : audacious-plugins
version    : '4.3'
release    : 49
source     :
    - https://distfiles.audacious-media-player.org/audacious-plugins-4.3.tar.bz2 : 662ef6c8c4bd70d0f35fd1c5f08b91549b9436638b65f8a1a33956b09df89fc6
homepage   : https://audacious-media-player.org/
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Plugins for Audacious music player
description: |
    Plugins for Audacious music player.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(alsa)
    - pkgconfig(audacious)
    - pkgconfig(faad2)
    - pkgconfig(fluidsynth)
    - pkgconfig(libavcodec)
    - pkgconfig(libcddb)
    - pkgconfig(libcdio_cdda)
    - pkgconfig(libcue)
    - pkgconfig(libcurl)
    - pkgconfig(libmms)
    - pkgconfig(libnotify)
    - pkgconfig(libopenmpt)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(neon)
    - pkgconfig(opusfile)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(soxr)
    - pkgconfig(wavpack)
    - pkgconfig(x11)
    - lame-devel
optimize   : lto
setup      : |
    %meson_configure -Dgtk=false
build      : |
    %ninja_build
install    : |
    %ninja_install
