name       : audacious-plugins
version    : 3.8.2
release    : 11
source     :
    - http://distfiles.audacious-media-player.org/audacious-plugins-3.8.2-gtk3.tar.bz2 : 7849024beae61b8af3874b166cf3977905aec77859e53901158b531b31ef0cef
license    : GPL-3.0
component  : multimedia.audio
summary    : Plugins for Audacious music player.
description: |
    Plugins for Audacious music player.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(audacious)
    - pkgconfig(flac)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libmpg123)
    - pkgconfig(libpulse)
    - pkgconfig(neon)
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - faad-devel
    - ffmpeg-devel
setup      : |
    %configure  --prefix=/usr
build      : |
    %make
install    : |
    %make_install
