name       : audacious-plugins
version    : 3.10.1
release    : 31
source     :
    - https://github.com/audacious-media-player/audacious-plugins/archive/audacious-plugins-3.10.1.tar.gz : 548fd3dd56da5e2f719844fb3dc5c53925a8f0fff21646fc8f88ff41880586e0
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Plugins for Audacious music player
description: |
    Plugins for Audacious music player.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(audacious)
    - pkgconfig(dbus-1)
    - pkgconfig(flac)
    - pkgconfig(fluidsynth)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libcue)
    - pkgconfig(libcurl)
    - pkgconfig(libcdio)
    - pkgconfig(libcdio_cdda)
    - pkgconfig(libcddb)
    - pkgconfig(libmms)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpg123)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(neon)
    - pkgconfig(ogg)
    - pkgconfig(sdl2)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - faad-devel
    - lame-devel
setup      : |
    %autogen --disable-qt --enable-gtk
build      : |
    %make
install    : |
    %make_install
