name       : audacious-plugins
version    : 3.7
release    : 3
source     :
    - http://distfiles.audacious-media-player.org/audacious-plugins-3.7-gtk3.tar.bz2 : d64fa6d1047edb4ebb74759470be869e3f883f7fb88f023f443350e4193c126d
license    : GPL-3.0 
summary    : Plugins for Audacious music player.
description: |
    Plugins for Audacious music player.
rundeps    :
    - audacious
builddeps  :
    - pkgconfig(audacious)
    - pkgconfig(libmpg123)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - pkgconfig(flac)
    - faad-devel
    - ffmpeg-devel
    - pkgconfig(neon)
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
setup      : |
    %configure  --prefix=/usr
build      : |
    %make
install    : |
    %make_install
