name       : audacious-plugins
version    : 3.7.2
release    : 8
source     :
    - http://distfiles.audacious-media-player.org/audacious-plugins-3.7.2-gtk3.tar.bz2 : 5b6c17b6f97ec0e123c59af16b71de6da0ed79327d21fcba9865a8742950b33f
license    : GPL-3.0
component  : multimedia.audio
summary    : Plugins for Audacious music player.
description: |
    Plugins for Audacious music player.
rundeps    :
    - audacious
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(audacious)
    - pkgconfig(flac)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmpg123)
    - pkgconfig(libpulse)
    - pkgconfig(neon)
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - faad-devel
    - ffmpeg-devel
setup      : |
    %configure  --prefix=/usr
build      : |
    %make
install    : |
    %make_install
