name       : audacious-plugins
version    : 4.0.5
release    : 40
source     :
    - https://distfiles.audacious-media-player.org/audacious-plugins-4.0.5.tar.bz2 : 9f0251922886934f2aa32739b5a30eadfefa7c70dd7b3e78f94aa6fc54e0c55b
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Plugins for Audacious music player
description: |
    Plugins for Audacious music player.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(alsa)
    - pkgconfig(audacious)
    - pkgconfig(flac)
    - pkgconfig(fluidsynth)
    - pkgconfig(libavcodec)
    - pkgconfig(libcddb)
    - pkgconfig(libcdio_cdda)
    - pkgconfig(libcue)
    - pkgconfig(libcurl)
    - pkgconfig(libmms)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpg123)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(neon)
    - pkgconfig(samplerate)
    - pkgconfig(sdl2)
    - pkgconfig(sndfile)
    - pkgconfig(soxr)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - faad-devel
    - lame-devel
optimize   : lto
setup      : |
    %autogen --enable-qt --disable-gtk
build      : |
    %make
install    : |
    %make_install
