name       : audacious-plugins
version    : 3.6.2
release    : 2
source     :
    - http://distfiles.audacious-media-player.org/audacious-plugins-3.6.2-gtk3.tar.bz2 : 943d94c1ea09817caba627b6abbf0de301c3cd19f2c8c0afae1ebc4dbe31fc95
license    : GPL-3.0 
summary    : Plugins for Audacious music player.
description: |
    Plugins for Audacious music player.
clang      : no
rundeps    :
    - audacious
builddeps  :
    - pkgconfig(audacious)
    - pkgconfig(libmpg123)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - pkgconfig(flac)
    - faad-devel
    - ffmpeg-devel
    - pkgconfig(neon)
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
setup      : |
    %configure  --prefix=/usr
build      : |
    %make
install    : |
    %make_install
